In [3]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
# 1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [7]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [10]:
# 5. 7 równomiernych punktów od 0 do 1
procenty = np.linspace(0, 1, 7)
print(f"Procenty: {procenty}")

Procenty: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [11]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [12]:
# Zbadaj tablicę losowych ocen
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


In [13]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy:                     0     1    2    3    4    5    6    7    8    9   10   11
# Miesiące:                  Sty  Lut  Mar  Kwi  Maj  Cze  Lip  Sie  Wrz  Paź  Lis  Gru

In [14]:
print(miesiace_sprzedaz[0])

120


In [15]:
print(miesiace_sprzedaz[-1])

221


In [19]:
print(miesiace_sprzedaz[0:2])

[120 135]


In [20]:
print(miesiace_sprzedaz[-3:])

[143 198 221]


In [26]:
print(miesiace_sprzedaz[::2])

[120  98 167 201 156 198]


In [28]:
print(miesiace_sprzedaz[::-1])

[221 198 143 156 178 201 189 167 142  98 135 120]


In [29]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
    [120, 145, 167],   # Produkt A
    [89,  102, 95],    # Produkt B
    [234, 267, 289],   # Produkt C
    [56,  78,  91],    # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

In [32]:
print(dane[0, 1])

145


In [35]:
print(dane[2])

[234 267 289]


In [36]:
print(dane[:, 0])

[120  89 234  56]


In [39]:
wycinek = dane[1:3, 1:3]

print(wycinek)

[[102  95]
 [267 289]]


In [6]:
# Produkty w sklepie internetowym
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
         'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']

ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

In [ ]:
### ZADANIE 6 (BONUS)

## Analiza korelacji cena-ocena

# Które produkty są "okazją" — ocena >= 4.5 i cena < 1000 zł? Wypisz nazwy i ceny.
# Jaka jest średnia cena produktów z oceną >= 4.0 vs < 4.0?
# Podpowiedź: łączenie warunków: (warunek1) & (warunek2)

przefiltrowane_ponizej = [x for x in oceny_klientow if x < 4.0]
przefiltrowane_powyzej = [x for x in oceny_klientow if x >=4.0]

for i in range(len(nazwy)):
    if oceny_klientow[i] >= 4.0:
      print("---PRODUKTY Z OKAZJA---")
      if ceny[i] < 1000:
         print("Nazwa produktu: ", nazwy[i])
         print("Cena: ", ceny[i])
   
srednia_powyzej = sum(przefiltrowane_powyzej) / len(przefiltrowane_powyzej)
print("Średnia cen produktów powyżej oceny 4.0: ", srednia_powyzej)
srednia_ponizej = sum(przefiltrowane_ponizej) / len(przefiltrowane_ponizej)
print("Średnia cen produktów ponizej oceny 4.0: ", srednia_ponizej)

    
       

        

---PRODUKTY Z OKAZJA---
---PRODUKTY Z OKAZJA---
---PRODUKTY Z OKAZJA---
---PRODUKTY Z OKAZJA---
Nazwa produktu:  Słuchawki
Cena:  349
---PRODUKTY Z OKAZJA---
Nazwa produktu:  Klawiatura
Cena:  249
---PRODUKTY Z OKAZJA---
Nazwa produktu:  Mysz
Cena:  129
---PRODUKTY Z OKAZJA---
Powyżej:  4.2
Poniżej:  3.8


In [25]:
###ZADANIE 5
#Analiza zapasów


# Produkty z niskim stanem magazynowym (< 30 szt.) — nazwy
# Łączna wartość tych produktów
# Ile % całego magazynu stanowią?
wartosc_produktow         = 0
ilosc_czesciowy_produktow = 0

for i in range(len(nazwy)):
    if ilosci_magazyn[i] < 30:
        print("Nazwa produktu: ", nazwy[i])
        print("Cena produktu: ", ceny[i])
        print("Ilość w magazynie: ", ilosci_magazyn[i])

        ilosc_czesciowy_produktow =+ ilosci_magazyn[i]
        wartosc_produktow         =+ ceny[i]

suma_produktow = ilosci_magazyn.sum()
procent        = (ilosc_czesciowy_produktow / suma_produktow ) * 100       
print("Łączna wartość owych produktów: ", wartosc_produktow)
print("Procent produktów z całego magazynu: ", procent)

Nazwa produktu:  Laptop
Cena produktu:  3499
Ilość w magazynie:  15
Nazwa produktu:  Monitor
Cena produktu:  1499
Ilość w magazynie:  23
Łączna wartość owych produktów:  1499
Procent produktów z całego magazynu:  2.3115577889447234


In [22]:
###ZADANIE 4
#Filtrowanie
 
print("---PRODUKTY ZACZYNAJACE SIE OD OCENY 4.5---")
for i in range(9):
 
 if oceny_klientow[i] >= 4.5:
    
  print("Nazwa produktu: ", nazwy[i])
  print("Cena produktu: ", ceny[i])

print("---PRODUKTY PONIŻEJ 200 ZŁ---")
for i in range(9):
 
 if ceny[i] < 200:
  
  print("Nazwa produktu: ", nazwy[i])
  print("Cena produktu: ", ceny[i])
  print("Ilość w magazynie: ", ilosci_magazyn[i])
  




---PRODUKTY ZACZYNAJACE SIE OD OCENY 4.5---
Nazwa produktu:  Laptop
Cena produktu:  3499
Nazwa produktu:  Smartfon
Cena produktu:  2499
Nazwa produktu:  Słuchawki
Cena produktu:  349
Nazwa produktu:  Monitor
Cena produktu:  1499
---PRODUKTY PONIŻEJ 200 ZŁ---
Nazwa produktu:  Ładowarka
Cena produktu:  89
Ilość w magazynie:  312
Nazwa produktu:  Mysz
Cena produktu:  129
Ilość w magazynie:  201


In [6]:
print(ceny.mean())

1171.0


In [4]:
import numpy as np


In [ ]:
### Zadanie 2
# Wartość magazynu
wartosc_magazynu = 0

for i in range(10):
    print("Nazwa produktu: ", nazwy[i])
    print("Wartość produktu: ", ceny[i] * ilosci_magazyn[i])

    suma = ceny[i] * ilosci_magazyn[i] 
  

    wartosc_magazynu += suma
    

print("Wartość magazynu: ", wartosc_magazynu)    


Nazwa produktu:  Laptop
Wartość produktu:  52485
Nazwa produktu:  Tablet
Wartość produktu:  79758
Nazwa produktu:  Smartfon
Wartość produktu:  194922
Nazwa produktu:  Słuchawki
Wartość produktu:  54444
Nazwa produktu:  Ładowarka
Wartość produktu:  27768
Nazwa produktu:  Klawiatura
Wartość produktu:  22161
Nazwa produktu:  Mysz
Wartość produktu:  25929
Nazwa produktu:  Monitor
Wartość produktu:  34477
Nazwa produktu:  Kamera
Wartość produktu:  26955
Nazwa produktu:  Drukarka
Wartość produktu:  30566
Wartość magazynu:  549465


In [ ]:
print(miesiace_sprzedaz[-3:])

In [ ]:
###Zadanie 3

#CENY PO RABACIE 15%
print("---CENY PO RABACIE 15 %---")
for i in range(9):
 
  print("---")
  print("Nazwa produktu: ", nazwy[i])
  print("Cena po rabcie: ", ceny[i] * 0.85)
  print("----")

#CENY Z VAT 23%
print("---CENY Z VAT 23%---")
for i in range(9):
 
  print("---")
  print("Nazwa produktu: ", nazwy[i])
  print("Cena z VAT 23%: ", ceny[i] * 1.23)
  print("----")

#ILOŚĆ PRODUKTÓW POWYŻEJ 1000 ZŁ
print("ILOŚĆ PRODUKTÓW POWYŻEJ 1000 ZŁ")

warunek = ceny > 1000
liczba_drogich = warunek.sum()

print(f"Liczba produktów droższych niż 1000 zł: {liczba_drogich}")



---CENY PO RABACIE 15 %---
---
Nazwa produktu:  Laptop
Cena po rabcie:  2974.15
----
---
Nazwa produktu:  Tablet
Cena po rabcie:  1614.1499999999999
----
---
Nazwa produktu:  Smartfon
Cena po rabcie:  2124.15
----
---
Nazwa produktu:  Słuchawki
Cena po rabcie:  296.65
----
---
Nazwa produktu:  Ładowarka
Cena po rabcie:  75.64999999999999
----
---
Nazwa produktu:  Klawiatura
Cena po rabcie:  211.65
----
---
Nazwa produktu:  Mysz
Cena po rabcie:  109.64999999999999
----
---
Nazwa produktu:  Monitor
Cena po rabcie:  1274.1499999999999
----
---
Nazwa produktu:  Kamera
Cena po rabcie:  509.15
----
---CENY Z VAT 23%---
---
Nazwa produktu:  Laptop
Cena z VAT 23%:  4303.7699999999995
----
---
Nazwa produktu:  Tablet
Cena z VAT 23%:  2335.77
----
---
Nazwa produktu:  Smartfon
Cena z VAT 23%:  3073.77
----
---
Nazwa produktu:  Słuchawki
Cena z VAT 23%:  429.27
----
---
Nazwa produktu:  Ładowarka
Cena z VAT 23%:  109.47
----
---
Nazwa produktu:  Klawiatura
Cena z VAT 23%:  306.27
----
---
Nazwa p

In [9]:
#średnia
print("Ceny", ceny.mean())
print("Ilosci_magazyn", ilosci_magazyn.mean())
print("oceny klientow", oceny_klientow.mean())
#max
print("Ceny", ceny.max())
print("Ilosci_magazyn", ilosci_magazyn.max())
print("Oceny_klientow", oceny_klientow.max())
#min
print("Ceny", ceny.min())
print("Ilosci_magazyn", ilosci_magazyn.min())
print("Oceny_klientow", oceny_klientow.min())

Ceny 1171.0
Ilosci_magazyn 99.5
oceny klientow 4.24
Ceny 3499
Ilosci_magazyn 312
Oceny_klientow 4.8
Ceny 89
Ilosci_magazyn 15
Oceny_klientow 3.5


In [5]:
import numpy as np

# Zjazd 3, część 1 — NumPy
**Autor:** Twoje Imię i Nazwisko