# Zjazd 3, część 2 — NumPy zaawansowane
**Autor:** Piotr Wdowiński

In [1]:
import numpy as np


In [3]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99],    # Produkt A
                  [49.99, 52.99, 47.99],    # Produkt B
                  [14.99, 15.99, 13.99],    # Produkt C
                  [99.99, 104.99, 94.99]])  # Produkt D

sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}")  # (4, 3)

Kształt macierzy: (4, 3)


In [ ]:
#Zadanie 1a

ceny_po_inflacji = ceny * 1.05

print(ceny_po_inflacji)

[[ 31.4895  33.5895  30.4395]
 [ 52.4895  55.6395  50.3895]
 [ 15.7395  16.7895  14.6895]
 [104.9895 110.2395  99.7395]]


In [19]:
#Zadanie 1b

rabaty = np.array([0.10, 0.05, 0.15])
x = 0
#centrum = ceny[:, 0] * (1 - rabaty[0])

for name in sklepy:
    print(name, " ceny po rabacie: ", ceny[:, x] * (1 - rabaty[x]))
    x = x + 1
    

Centrum  ceny po rabacie:  [26.991 44.991 13.491 89.991]
Galeria  ceny po rabacie:  [30.3905 50.3405 15.1905 99.7405]
Online  ceny po rabacie:  [24.6415 40.7915 11.8915 80.7415]


In [24]:
#Zadanie 1c
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
x = 0

for produkt in produkty:
    print("Kosztu Produkt ", produkt, " cena produktu po przeliczeniu marży: ", ceny[x, :] / (1 + marza[x]))
    x = x + 1



Kosztu Produkt  A  cena produktu po przeliczeniu marży:  [23.06923077 24.60769231 22.3       ]
Kosztu Produkt  B  cena produktu po przeliczeniu marży:  [35.70714286 37.85       34.27857143]
Kosztu Produkt  C  cena produktu po przeliczeniu marży:  [11.992 12.792 11.192]
Kosztu Produkt  D  cena produktu po przeliczeniu marży:  [66.66       69.99333333 63.32666667]


In [28]:
#Zadanie 1d

print(ceny.argmin(axis=1))

[2 2 2 2]


Ćwiczenie 2: Reshape i łączenie danych (20 min)

In [4]:
#Zadanie 2a — Reshape

# Dane miesięczne z jednego roku (flat)
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])

# Przekształć na kwartały (4 kwartały × 3 miesiące)
kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


In [5]:
#Zadanie 2b — Stacking

# Dane z 3 oddziałów (osobne tablice)
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])

# Połącz w macierz (3 oddziały × 4 kwartały)
wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")

Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


In [14]:
#Zadanie 2c — Praktyczne (samodzielnie)

# Masz dane o sprzedaży 6 produktów jako wektor
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])
# Wiesz, że to 6 produktów × 2 miesiące

# 1. Reshape na macierz 6×2
# Podpowiedź: sprzedaz_flat.reshape(6, 2) albo .reshape(-1, 2)
zadanie_1 = sprzedaz_flat.reshape(6, 2)

# 2. Oblicz średnią sprzedaż per produkt (axis=1)
produkt1 = np.mean(zadanie_1, axis=1)

print(produkt1)



# 3. Oblicz zmianę między miesiącem 1 a 2 (kolumna 1 - kolumna 0)
# Podpowiedź: macierz[:, 1] - macierz[:, 0]

wynik = zadanie_1[:, 1] - zadanie_1[:, 0]

print(wynik)

[150. 225. 215. 170. 240. 225.]
[100 150 -70 100 140 -70]


In [19]:
#Zadanie 2d — Flatten i concatenate

# Masz macierz kwartałów z zadania 2a
# 1. Spłaszcz ją z powrotem do wektora (.flatten())
powrotny_wektor = kwartaly.flatten()
# 2. Dodaj dane z 13. miesiąca (wartość: 235) — np.concatenate()
trzynasty_miesiac = np.array([235])

nowy_wynik = np.concatenate((dane_flat, trzynasty_miesiac))

print(nowy_wynik)

# Podpowiedź: np.concatenate([wektor, np.array([235])])

[120 135  98 142 167 189 201 178 156 143 198 221 235]


Ćwiczenie 3: Analiza danych finansowych (30 min)

In [2]:
np.random.seed(2026)

# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])

# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

In [26]:
#Zadanie 3a: Analiza wynagrodzeń

# 1. Oblicz średnią, medianę i odchylenie standardowe pensji
# Podpowiedź: pensje.mean(), np.median(pensje), pensje.std()
srednia    = pensje.mean()
mediana    = np.median(pensje)
odchylenie = np.std(pensje)

print("ŚREDNIA: ", srednia, " MEDIANA: ", mediana, " ODCHYLENIE: ", odchylenie)

# 2. Wyświetl imiona osób zarabiających powyżej średniej
# Uwaga: pracownicy to lista — zamień na np.array(pracownicy), żeby użyć maski
# Podpowiedź: nazwy = np.array(pracownicy), potem nazwy[pensje > pensje.mean()]

pracownicy2      = np.array(pracownicy)
wynik_pracownicy = pracownicy2[pensje > pensje.mean()]
print(wynik_pracownicy)

# 3. Wyświetl imiona osób zarabiających poniżej mediany

ponizej_mediany = pracownicy2[pensje < np.median(pensje)]
print(ponizej_mediany)

# 4. Oblicz rozstęp (max - min) i rozstęp międzykwartylowy (IQR)
# Podpowiedź: IQR = np.percentile(pensje, 75) - np.percentile(pensje, 25)

iqr = np.percentile(pensje, 75) - np.percentile(pensje, 25)
print(iqr)

ŚREDNIA:  6425.0  MEDIANA:  6050.0  ODCHYLENIE:  1616.9029037020127
['Jan' 'Marek' 'Zofia']
['Anna' 'Ewa' 'Piotr' 'Tomek']
2200.0


In [3]:
#Zadanie 3b: System premii (np.where)

# Zasady premii:
# - ocena >= 4.5 → premia 2000 zł
# - ocena >= 4.0 → premia 1000 zł
# - ocena < 4.0 → premia 0 zł
# Podpowiedź: zagnieżdżony where:
#   np.where(oceny >= 4.5, 2000, np.where(oceny >= 4.0, 1000, 0))

premia = np.where(oceny >= 4.5, 2000, np.where(oceny >= 4.0, 1000, 0))

nowe_wynagrodzenie = pensje + premia

print(nowe_wynagrodzenie)

# Oblicz nowe wynagrodzenie (pensja + premia)
# Kto dostał najwyższą premię? Użyj argmax()

indeks_max = np.argmax(premia)
zwyciezca = pracownicy2[indeks_max]

print(zwyciezca)


NameError: name 'oceny' is not defined

In [ ]:
#Zadanie 3c: Ranking (argsort)

# Posortuj pracowników wg pensji (od najwyższej)
# Podpowiedź: kolejnosc = np.argsort(pensje)[::-1]
# Wyświetl ranking: pozycja, imię, pensja, staż
# Podpowiedź: for i, idx in enumerate(kolejnosc, 1): ...

kolejnosc = np.argsort(pensje)[::-1]

for i, idx in enumerate(kolejnosc, 1):
    print("Pozycja: ", i, "Imie: ", pracownicy[idx], " Pensja: ", pensje[idx], " Staż: ", staz[idx])

print(kolejnosc)

Pozycja:  1 Imie:  Marek  Pensja:  9100  Staż:  15
Pozycja:  2 Imie:  Zofia  Pensja:  8500  Staż:  12
Pozycja:  3 Imie:  Jan  Pensja:  7200  Staż:  8
Pozycja:  4 Imie:  Kasia  Pensja:  6300  Staż:  5
Pozycja:  5 Imie:  Tomek  Pensja:  5800  Staż:  4
Pozycja:  6 Imie:  Anna  Pensja:  5500  Staż:  3
Pozycja:  7 Imie:  Ewa  Pensja:  4800  Staż:  2
Pozycja:  8 Imie:  Piotr  Pensja:  4200  Staż:  1
[3 6 1 4 7 0 2 5]


In [11]:
#Zadanie 3d: Korelacja

# Oblicz korelację: staż vs pensja
# Podpowiedź: np.corrcoef(staz, pensje)[0, 1]

# Oblicz korelację: staż vs ocena
# Który związek jest silniejszy? (wyższa wartość bezwzględna r)

korelacja  = np.corrcoef(staz, pensje)[0, 1]
korelacja2 = np.corrcoef(staz, oceny)[0, 1]

wynik = np.maximum(np.abs(korelacja), np.abs(korelacja2))
print("Korelacja między stażem, a pensja: ", korelacja, " Korelacja między stażem, a oceną: ", korelacja2, " Silniejszy związek to: ", wynik)

Korelacja między stażem, a pensja:  0.987862864584301  Korelacja między stażem, a oceną:  0.04198471605953068  Silniejszy związek to:  0.987862864584301


In [6]:
#Zadanie 3e: Analiza sprzedaży (broadcasting)

# Oblicz przychód: sprzedaz (4×6) * ceny_produktow (4,) — UWAGA na broadcasting!
# Problem: (4,6) * (4,) — nie pasuje! 6 != 4
# Rozwiązanie: ceny muszą być kolumną (4×1)
# Podpowiedź: ceny_kol = ceny_produktow.reshape(4, 1)
#             przychod = sprzedaz * ceny_kol

# Który produkt przyniósł największy łączny przychód? (axis=1, argmax)
# Który miesiąc był najlepszy łącznie? (axis=0, argmax)
# Trend: porównaj pierwsze 3 miesiące vs ostatnie 3
# Podpowiedź: przychod[:, :3].sum() vs przychod[:, 3:].sum()





ceny_kol = ceny_produktow.reshape(4, 1)
przychod = sprzedaz * ceny_kol

print(przychod)

laczny_przychod_produkty = przychod.sum(axis=1)
najlepszy_produkt_idx = laczny_przychod_produkty.argmax()

laczny_przychod_miesiace = przychod.sum(axis=0)
najlepszy_miesiac_idx = laczny_przychod_miesiace.argmax()

wynik = przychod[:, :3].sum()
wynik2 = przychod[:, 3:].sum()

print(wynik)
print(wynik2)

print("Macierz przychodu (4x6):\n", przychod)
print(f"\nNajlepszy produkt (indeks): {najlepszy_produkt_idx}")
print(f"Najlepszy miesiąc (indeks): {najlepszy_miesiac_idx}")
print(f"Przychód I połowa: {wynik} vs II połowa: {wynik2}")

if wynik2 > wynik:
    print("Trend: Sprzedaż rośnie!")
else:
    print("Trend: Sprzedaż maleje.")

[[ 73500 539000 161000 339500 339500 171500]
 [244800 316800 358200  86400 270000  84600]
 [ 67500 290000 387500 327500 420000 452500]
 [ 10200   8700   6750  13200  19800  12000]]
2463950
2536500
Macierz przychodu (4x6):
 [[ 73500 539000 161000 339500 339500 171500]
 [244800 316800 358200  86400 270000  84600]
 [ 67500 290000 387500 327500 420000 452500]
 [ 10200   8700   6750  13200  19800  12000]]

Najlepszy produkt (indeks): 2
Najlepszy miesiąc (indeks): 1
Przychód I połowa: 2463950 vs II połowa: 2536500
Trend: Sprzedaż rośnie!


Ćwiczenie 4: Generowanie danych (15 min)

In [7]:
#Krok 1 — Generowanie

np.random.seed(42)

# Wygeneruj dane o 100 klientach sklepu:
# - wiek: rozkład normalny, średnia 35, std 10, zaokrąglony do int, min 18
# - wydatki_miesiecznie: rozkład normalny, średnia 500, std 200, min 0
# - liczba_wizyt: rozkład Poissona, lambda=5

# Podpowiedź: np.clip() ogranicza wartości do zakresu
wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)
wizyty = np.random.poisson(5, 100)

In [ ]:
#Krok 2 — Analiza (samodzielnie)

# 1. Statystyki opisowe każdej zmiennej (mean, median, std, min, max)
# Podpowiedź: print(f"Wiek — średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}")

# 2. Korelacja wiek vs wydatki
# Podpowiedź: np.corrcoef(wiek, wydatki)[0, 1]

# 3. Korelacja wizyty vs wydatki

# 4. Segmentacja klientów za pomocą np.where:
#    - "WYSOKI" gdy wydatki > średnia + std
#    - "NISKI" gdy wydatki < średnia - std
#    - "ŚREDNI" w pozostałych przypadkach
# Podpowiedź: zagnieżdżony np.where (jak w zadaniu 3b)
#   sr = wydatki.mean()
#   sd = wydatki.std()
#   segment = np.where(wydatki > sr + sd, 'WYSOKI', np.where(wydatki < sr - sd, 'NISKI', 'ŚREDNI'))

# 5. Ile klientów w każdym segmencie? Użyj np.unique(..., return_counts=True)

print(f"Wiek — średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}")

wynik_korelacja  = np.corrcoef(wiek, wydatki)[0, 1]
wynik_korelacja2 = np.corrcoef(wizyty, wydatki)[0, 1]


print(wynik_korelacja)
print(wynik_korelacja2)


sr = wydatki.mean()
sd = wydatki.std()

segment = np.where(wydatki > sr + sd, 'WYSOKI', np.where(wydatki < sr - sd, 'NISKI', 'ŚREDNI'))

klienci, liczniki = np.unique(segment, return_counts=True)
print(liczniki)


Wiek — średnia: 33.6, mediana: 33.0
-0.12009183441777695
-0.15884985147948125
[17 12 71]
